import type { Product } from "./types";

export const CATALOG: Product[] = [
  {
    article: "A112T4",
    name: "ботинки kari",
    description: "женские ботинки демисезонные kari",
    manufacturer: "Kari",
    supplier: "Kari",
    category: "женская обувь",
    unit: "шт.",
    price: 4990,
    discountPercent: 3,
    stockCount: 6,
    imagePath: "/1.jpg",
  },
  {
    article: "F635R4",
    name: "ботинки marco tozzi",
    description: "ботинки marco tozzi женские демисезонные, размер 39, цвет бежевый",
    manufacturer: "Marco Tozzi",
    supplier: "Обувь для вас",
    category: "женская обувь",
    unit: "шт.",
    price: 3244,
    discountPercent: 2,
    stockCount: 13,
    imagePath: "/2.jpg",
  },
  {
    article: "H782T5",
    name: "туфли kari",
    description: "туфли kari мужские классика, размер 43, цвет: черный",
    manufacturer: "Kari",
    supplier: "Kari",
    category: "мужская обувь",
    unit: "шт.",
    price: 4499,
    discountPercent: 5,
    stockCount: 5,
    imagePath: "/3.jpg",
  },
  {
    article: "G783F5",
    name: "ботинки рос",
    description: "мужские ботинки рос-обувь кожаные с натуральным мехом",
    manufacturer: "Рос",
    supplier: "Kari",
    category: "мужская обувь",
    unit: "шт.",
    price: 5900,
    discountPercent: 2,
    stockCount: 8,
    imagePath: "/4.jpg",
  },
  {
    article: "J384T6",
    name: "ботинки rieker",
    description: "b3430/14 полуботинки мужские rieker",
    manufacturer: "Rieker",
    supplier: "Обувь для вас",
    category: "мужская обувь",
    unit: "шт.",
    price: 3800,
    discountPercent: 0,
    stockCount: 16,
    imagePath: "/5.jpg",
  },
  {
    article: "F572H7",
    name: "кроссовки kari",
    description: "кроссовки kari женские легкие на каждый день",
    manufacturer: "Kari",
    supplier: "Kari",
    category: "женская обувь",
    unit: "шт.",
    price: 2790,
    discountPercent: 8,
    stockCount: 0,
    imagePath: "/6.jpg",
  },
  {
    article: "D329H3",
    name: "сапоги marco tozzi",
    description: "сапоги marco tozzi зимние, высокий голенищный силуэт",
    manufacturer: "Marco Tozzi",
    supplier: "Обувь для вас",
    category: "женская обувь",
    unit: "шт.",
    price: 6790,
    discountPercent: 17,
    stockCount: 9,
    imagePath: "/7.jpg",
  },
  {
    article: "K901P2",
    name: "кеды rieker",
    description: "кеды rieker женские, удобная посадка и мягкая подошва",
    manufacturer: "Rieker",
    supplier: "Kari",
    category: "женская обувь",
    unit: "шт.",
    price: 5290,
    discountPercent: 20,
    stockCount: 2,
    imagePath: "/8.jpg",
  },
];

